name: dual_custom_date_picker
description: "A flutter package for custom Jalali and Georgian date picker"
version: 1.2.1
homepage: https://github.com/Arefyazdkhasti/custom_date_picker

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  persian_number_utility: ^1.1.6
  shamsi_date: ^1.1.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - screenshots/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Iconsax
      fonts:
        - asset: fonts/Iconsax.ttf
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package